name: Common Test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: ['23.1', '22.3.4.2', '21.3.8.16', '20.3.8.21']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: bajankristof/setup-erlang@master
      with:
        otp-version: ${{ matrix.otp_version }}

    - name: Compile
      run: rebar3 compile
    - name: EUnit tests
      run: rebar3 eunit
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: XRef
      run: rebar3 xref

    - name: Covertool
      if: ${{ always() }}
      run: rebar3 covertool generate
    - uses: codecov/codecov-action@v1
      with:
        file: _build/test/covertool/elli.covertool.xml
        env_vars: OTP_VERSION
